Add Sample Site and Ci Support (#25)
* add db initialization script

* fix docker build error

* test

* fix bms.war does not exit error

* test

* test

* test

* test

* fix file not found exception

* deploy services to the server

* fix syntax error

* fix some problems

* test

* test

* test

* fix problems in docker-compose.yml

* fix problems in docker-compose.yml

* fix docker-compose.yml can not use env

* fix use --env-file to support env

* test

* change data source setting

* fix NoClassDefFoundError

* fix problems caused by upgrading spring 5.x to 6.x

* test

* test

* test

* test

* test

* test

* test

* test

* fix package problem

* fix syntax error

* fix mysql connect deny problem

* fix WeakKeyException